import type { ProvenanceItem } from './audit-types.ts';

const choice = (
  id: string,
  name: string,
  value: unknown,
  file: string,
  line: number,
  needle: string,
  impact: ProvenanceItem['impact'],
  subsystem: string,
  defect?: string,
): ProvenanceItem => ({
  id: `choice.${id}`,
  name,
  value,
  provenance: 'arbitrary-model',
  impact,
  subsystem,
  source: { file: `cleanroom/src/${file}`, line, needle },
  sensitivity: 'unmeasured',
  defect,
});

const resolved = (item: ProvenanceItem): ProvenanceItem => ({ ...item, defectStatus: 'resolved' });

export const CONTROL_CHOICES: readonly ProvenanceItem[] = [
  choice('air-filter', 'air-mass first-order filter shift', 3, 'subsystems/air-mass.ts', 19, 'FILTER_SHIFT', 'control-equation', 'air-mass'),
  choice('sync-state-values', 'lost/acquiring/locked state encoding', [0, 1, 2], 'subsystems/crank-sync.ts', 25, 'SYNC_STATE', 'state-layout', 'crank-sync'),
  choice('sync-lock-threshold', 'plausible captures required for lock', 4, 'subsystems/crank-sync.ts', 28, 'LOCK_THRESHOLD', 'threshold', 'crank-sync'),
  choice('sync-period-ratio', 'period ratio allowed before lock loss', 4, 'subsystems/crank-sync.ts', 30, 'PLAUSIBLE_RATIO', 'threshold', 'crank-sync'),
  choice('load-equation', 'normalized load equation', 'round(filteredAirMassByte*176/max(1,speedCount))', 'subsystems/engine-load.ts', 70, 'LOAD_GAIN', 'control-equation', 'load'),
  choice('load-gain', 'normalized load gain', 176, 'subsystems/engine-load.ts', 43, 'LOAD_GAIN', 'control-equation', 'load'),
  choice('mode-thresholds', 'operating-mode thresholds', { crankingRpm: 400, idleUpperRpm: 1100, idleUpperLoad: 0x50, wotLoad: 0xc0 }, 'subsystems/engine-load.ts', 32, 'THRESHOLDS', 'threshold', 'load'),
  choice('mode-encoding', 'mode-field numeric encoding', { stopped: 0, cranking: 1, idle: 2, partLoad: 3, wot: 4 }, 'subsystems/engine-load.ts', 86, 'const index', 'state-layout', 'load'),
  choice('load-percent-view', 'normalized load API percent equation', 'raw*100/255', 'subsystems/sensor-state.ts', 112, '100', 'api-confidence', 'sensors'),
  resolved(choice('scaled-confidence-supply', 'supply volts API confidence', 'unknown', 'subsystems/sensor-state.ts', 69, "confidence: 'unknown'", 'api-confidence', 'sensors', 'Previously claimed medium confidence despite arbitrary transfer assumptions.')),
  resolved(choice('scaled-confidence-coolant', 'coolant degrees API confidence', 'unknown', 'subsystems/sensor-state.ts', 79, "confidence: 'unknown'", 'api-confidence', 'sensors', 'Previously claimed medium confidence despite arbitrary transfer assumptions.')),
  resolved(choice('scaled-confidence-air', 'intake-air degrees API confidence', 'unknown', 'subsystems/sensor-state.ts', 89, "confidence: 'unknown'", 'api-confidence', 'sensors', 'Previously claimed medium confidence despite arbitrary transfer assumptions.')),
  resolved(choice('scaled-confidence-rpm', 'RPM API confidence', 'unknown', 'subsystems/sensor-state.ts', 100, "confidence: 'unknown'", 'api-confidence', 'speed', 'Previously claimed medium confidence despite unproven timing and scaling.')),
  choice('fuel-part-load-edge', 'direct part-load base edge', 'master slot 40', 'subsystems/fuel-control.ts', 51, 'partLoadBase', 'calibration', 'fuel'),
  choice('fuel-transient-delta', 'transient enrichment input', 'sat8(abs(load-lastLoad)*8)', 'subsystems/fuel-control.ts', 125, 'Math.abs', 'control-equation', 'fuel'),
  choice('fuel-correction-order', 'fuel correction order', [18, 20, 16], 'subsystems/fuel-control.ts', 137, 'const terms', 'control-equation', 'fuel'),
  choice('fuel-correction-product', 'fuel correction fold', 'sat8(high8(composite,term)*2)', 'subsystems/fuel-control.ts', 144, 'for (const term', 'control-equation', 'fuel'),
  choice('fuel-transient-blend', 'transient added to correction', 'transient >> 2', 'subsystems/fuel-control.ts', 145, 'transient >> 2', 'control-equation', 'fuel'),
  choice('fuel-pulse-equation', 'final pulse-count equation', 'sat8(high8(base,correction)*2)', 'subsystems/fuel-control.ts', 94, 'pulseCount', 'control-equation', 'fuel'),
  choice('fuel-bank-count', 'every fuel dispatch emits two simultaneous banks', ['injector-bank-a', 'injector-bank-b'], 'subsystems/fuel-control.ts', 165, "['a', 'b']", 'actuator-wiring', 'fuel'),
  choice('fuel-cut-wiring', 'rev-limit and overrun latches directly suppress fuel', true, 'ecu-subsystems.ts', 67, 'const fuel', 'actuator-wiring', 'fuel'),
  choice('ignition-cut-wiring', 'rev-limit latch directly suppresses ignition', true, 'ecu-subsystems.ts', 61, 'new IgnitionControl', 'actuator-wiring', 'ignition'),
  choice('ignition-channels', 'ignition charge/fire compare channels', [2, 3], 'subsystems/ignition-control.ts', 34, 'SCHEDULED_COMPARE_CHANNELS', 'actuator-wiring', 'ignition', 'Binary hardware model identifies Timer0/P1.5 as ignition and CC2/CC3 as injector banks.'),
  choice('ignition-advance-time', 'advance-to-segment timing equation', 'clamp(deg/(360/toothCount)/8,0,0.9)', 'subsystems/ignition-control.ts', 98, 'advanceFraction', 'control-equation', 'ignition'),
  choice('ignition-port-wiring', 'compare channel number is reused as P1 bit number', [2, 3], 'subsystems/ignition-control.ts', 136, 'setP1(chargeChannel', 'actuator-wiring', 'ignition'),
  choice('idle-default-inputs', 'idle transmission/A/C defaults', { parkNeutral: true, airConditioning: false }, 'subsystems/idle-control.ts', 52, 'private inputs', 'state-layout', 'idle'),
  choice('idle-initial-command', 'idle actuator initial command', 0x60, 'subsystems/idle-control.ts', 51, 'private actuator', 'control-equation', 'idle'),
  choice('idle-gains', 'idle proportional and integral gains', [0.6, 0.08], 'subsystems/idle-control.ts', 44, 'GAIN_PROPORTIONAL', 'control-equation', 'idle'),
  choice('idle-limits', 'idle actuator byte bounds', [0x10, 0xf0], 'subsystems/idle-control.ts', 46, 'ACTUATOR_MIN', 'threshold', 'idle'),
  choice('idle-integral-limit', 'idle integral clamp', [-400, 400], 'subsystems/idle-control.ts', 86, '-400', 'threshold', 'idle'),
  choice('idle-command-divisor', 'idle correction divisor', 32, 'subsystems/idle-control.ts', 87, '/ 32', 'control-equation', 'idle'),
  choice('overrun-thresholds', 'overrun qualifiers and debounce', { minimumRpm: 1500, maximumLoad: 0x18, minimumCoolant: 0x40, debounce: 4 }, 'subsystems/overrun-latch.ts', 20, 'const QUALIFY', 'threshold', 'overrun'),
  choice('adaptation-timings', 'adaptation stable/debounce passes', [6, 3], 'subsystems/adaptation.ts', 35, 'STABLE_DELAY_PASSES', 'threshold', 'adaptation'),
  choice('adaptation-limit-step', 'adaptation correction limit and step', [0x30, 2], 'subsystems/adaptation.ts', 37, 'CORRECTION_LIMIT', 'control-equation', 'adaptation'),
  choice('adaptation-region-map', 'idle maps to cellA and part-load to cellB', true, 'subsystems/adaptation.ts', 142, "operatingMode() === 'idle'", 'control-equation', 'adaptation'),
  choice('fault-channel-map', 'model fault IDs and fallback bytes', { supply: [0x11, 0xa0], intake: [0x12, 0x80], coolant: [0x13, 0x80], hysteretic: [0x14, 0x80], unresolved: [0x15, 0x80] }, 'subsystems/fault-monitors.ts', 41, 'MONITORED_CHANNELS', 'fault-behavior', 'faults'),
  choice('fault-rails', 'ADC fault rail thresholds', [0x02, 0xfd], 'subsystems/fault-monitors.ts', 50, 'LOWER_RAIL', 'threshold', 'faults'),
  choice('fault-qualification', 'out-of-range passes required for fault', 3, 'subsystems/fault-monitors.ts', 56, 'qualifyAfter', 'threshold', 'faults'),
  choice('fault-plausibility', 'opposite temperature rails trigger fault 0x16 subtype 3', true, 'subsystems/fault-monitors.ts', 93, 'coolant <=', 'fault-behavior', 'faults'),
  choice('fault-aging', 'inactive fault maximum age default', 40, 'subsystems/fault-memory.ts', 127, 'maximumAge = 40', 'threshold', 'faults'),
  choice('checksum-chunk', 'foreground checksum bytes per pass', 512, 'subsystems/integrity.ts', 107, 'bytesPerPass = 512', 'scheduler', 'integrity'),
];
