import type { OracleHook } from './signal-contract.ts';

export const oracleHooks: ReadonlyArray<OracleHook> = [
  {
    id: 'ignition-command',
    source: 'p1',
    mask: 0x20,
    role: 'Timer-0/P1.5 logical ignition command',
    expectation: 'record-transitions',
    evidence: ['ecu/e2e-analysis/subsystems/06-ignition-control.md:46-56'],
  },
  {
    id: 'iac-command',
    source: 'p1',
    mask: 0x80,
    role: 'Timer-1/P1.7 logical idle-actuator command',
    expectation: 'record-transitions',
    evidence: ['ecu/e2e-analysis/hardware-model.md:31-33'],
  },
  {
    id: 'compare-2-schedule',
    source: 'sfr-write',
    addresses: [0xc4, 0xc5],
    role: 'CC2 logical injector timing schedule',
    expectation: 'record-schedules',
    evidence: ['ecu/e2e-analysis/hardware-model.json:SFR:00c4-SFR:00c5'],
  },
  {
    id: 'compare-3-schedule',
    source: 'sfr-write',
    addresses: [0xc6, 0xc7],
    role: 'CC3 logical injector timing schedule',
    expectation: 'record-schedules',
    evidence: ['ecu/e2e-analysis/hardware-model.json:SFR:00c6-SFR:00c7'],
  },
  {
    id: 'discrete-output-write',
    source: 'xdata-write',
    addresses: [0xa040],
    role: 'A040 discrete output-latch write',
    expectation: 'record-values',
    evidence: ['ecu/e2e-analysis/hardware-model.md:107-110'],
  },
  {
    id: 'phase-output-write',
    source: 'xdata-write',
    addresses: [0xa041],
    role: 'A041 phase/output sequence-latch write',
    expectation: 'record-values',
    evidence: ['ecu/e2e-analysis/hardware-model.md:107-110'],
  },
  {
    id: 'fault-state',
    source: 'xdata-access',
    addresses: [0x00ec],
    ranges: [
      [0x00ed, 0x00f3],
      [0x0300, 0x03fe],
    ],
    role: 'Fault count, cache, and record-range activity',
    expectation: 'record-values',
    evidence: ['ecu/e2e-analysis/subsystems/09-adaptation-faults-fallbacks.md:23-54'],
  },
  {
    id: 'supervisor-progress',
    source: 'pc',
    addresses: [0x908d],
    role: 'Supervisor entry progress',
    expectation: 'record-progress',
    evidence: ['ecu/mame-sab80c535-lab/workstreams/accuracy-xdata/README.md:15-20'],
  },
  {
    id: 'cyclic-progress',
    source: 'pc',
    addresses: [0x601a],
    role: 'Foreground cyclic executive progress',
    expectation: 'record-progress',
    evidence: ['ecu/e2e-analysis/subsystems/01-reset-scheduler-interrupts.md:38-41'],
  },
];
